favourite_books_site/favouritebooks/books/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.BookMainPage.as_view(), name='home'),
    path('addbook/', views.AddBook.as_view(), name='add_book'),
    path('feedback/', views.Feedback.as_view(), name='feedback'),
    path('feedback-success/', views.FeedbackSuccess.as_view(), name='feedback_success'),
    path('books/', views.AllPublishedBooks.as_view(), name='books'),
    path('my-books/', views.UserBooks.as_view(), name='user_books'),
    path('my-books/tag/<str:tag_slug>/', views.UserBooksByGenres.as_view(), name='user_books_by_tag'),
    path('book/<slug:book_slug>/', views.DetailedBookInfo.as_view(), name='book'),
    path('comment/<int:comment_id>/delete/', views.DeleteCommentView.as_view(), name='delete_comment'),
    path('comment/<int:comment_id>/like/',views.LikeCommentView.as_view(), name='like_comment'),
    path('edit/<slug:book_slug>/', views.BookEdit.as_view(), name='edit_book'),
    path('edit-success/', views.BookEditSuccess.as_view(), name='edit_success'),
    path('delete/<slug:book_slug>/', views.BookDelete.as_view(), name='delete_book'),
    path('tag/<slug:tag_slug>/', views.BookGenres.as_view(), name='tag'),
]

favourite_books_site/favouritebooks/favouritebooks/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from books.views import page_not_found
from favouritebooks import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.ENABLE_DEBUG_TOOLBAR:
    urlpatterns += debug_toolbar_urls()

handler404 = page_not_found

admin.site.site_header = "Favourite Books administration panel"
admin.site.index_title = "Favourite Books administration"


favourite_books_site/favouritebooks/users/urls.py
from django.contrib.auth.views import (LogoutView, PasswordChangeDoneView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView)
from django.urls import path, reverse_lazy

from . import views
from .views import CustomPasswordResetView

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='home'), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('register-success/', views.RegisterUserSuccess.as_view(), name='register_success'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/',
        PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
        name='password_change_done'),
    path('password-reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/',
        PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
        name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                         success_url=reverse_lazy('users:password_reset_complete')),
        name='password_reset_confirm'),
    path('password_reset/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('profile/', views.UserProfile.as_view(), name='profile'),
]

favourite_books_site/favouritebooks/users/models.py
from django.db import models

favourite_books_site/favouritebooks/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import (AuthenticationForm, PasswordChangeForm,
                                       PasswordResetForm, UserCreationForm)
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Username/Email*', widget=forms.TextInput())
    password = forms.CharField(label='Password*', widget=forms.PasswordInput())

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']

class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label="Username*", widget=forms.TextInput())
    password1 = forms.CharField(label="Password*", widget=forms.PasswordInput())
    password2 = forms.CharField(label="Repeat password*", widget=forms.PasswordInput())

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'password1', 'password2']
        labels = {
            'email': 'E-mail*',
        }

        widgets = {
            'email': forms.TextInput(),
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("This E-mail already exists!")
        return email

class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(label='Username', widget=forms.TextInput())
    email = forms.CharField(disabled=True,
                            required=False,
                            label='E-mail',
                            widget=forms.TextInput(attrs={'style': 'color: #888888;'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']
        labels = {
            'first_name': 'Name',
            'last_name': 'Surname'
        }
        widgets = {
            'first_name': forms.TextInput(),
            'last_name': forms.TextInput(),
        }

class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label='Old password', widget=forms.PasswordInput())
    new_password1 = forms.CharField(label='New password', widget=forms.PasswordInput())
    new_password2 = forms.CharField(label='New password confirmation', widget=forms.PasswordInput())

class CustomPasswordResetForm(PasswordResetForm):
     def clean_email(self):
         email = self.cleaned_data.get('email')
         user = User.objects.filter(email=email).first()
         if not user:
            raise ValidationError('The user with this E-mail does not exist. Make sure the E-mail is correct.')
         return email

favourite_books_site/favouritebooks/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (LoginView, PasswordChangeView,
                                       PasswordResetView)
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView

from books.utils import DataMixin
from users.forms import (CustomPasswordResetForm, LoginUserForm,
                         ProfileUserForm, RegisterUserForm,
                         UserPasswordChangeForm)


class LoginUser(DataMixin, LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    page_title = 'Login'

class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    page_title = 'Register'
    success_url = reverse_lazy('users:register_success')

class RegisterUserSuccess(DataMixin, TemplateView):
    template_name = 'users/register_success.html'
    page_title = 'Success'

class UserProfile(LoginRequiredMixin, DataMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    page_title = 'User Profile'

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

class UserPasswordChange(DataMixin, PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy('users:password_change_done')
    template_name = 'users/password_change.html'
    page_title = 'Password change'


class CustomPasswordResetView(PasswordResetView):
     form_class = CustomPasswordResetForm
     template_name = 'users/password_reset.html'
     email_template_name = 'users/password_reset_email.html'
     success_url = reverse_lazy('users:password_reset_done')

favourite_books_site/favouritebooks/users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h2>Login</h2>

    <form method="post">
        {% csrf_token %}

        <input type="hidden" name="next" value="{{ next }}" />
        <div class="form-error">{{ form.non_field_errors}}</div>
        {% for form_item in form %}
            <p>
                <label class="form-label" for="{{ form_item.id_for_label }}">{{ form_item.label }}</label>
                {{ form_item }}
            </p>
            <div class="form-error">{{ form_item.errors }}</div>
        {% endfor %}

        <!-- Button -->
        <div class="col-12">
            <ul class="actions form-button">
                <li><input type="submit" value="Login" class="primary" /></li>
            </ul>

            <div class="social-auth-container">
                <p>
                    <a class="social-auth" href="{% url 'social:begin' 'github' %}">
                        <img class="social-image github"
                             src="{% static 'books/images/social-auth/github.png' %}" alt="github-auth">
                    </a>
                </p>
                <p>
                    <a class="social-auth" href="{% url 'social:begin' 'google-oauth2' %}">
                        <img class="social-image google"
                             src="{% static 'books/images/social-auth/google.png' %}" alt="google-auth">
                    </a>
                </p>
            </div>

            <p><a href="{% url 'users:password_reset' %}">Forgot your password?</a></p>
        </div>

    </form>

{% endblock %}

favourite_books_site/favouritebooks/users/templates/users/password_change.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h2>Password change</h2>

    <form method="post">
        {% csrf_token %}

        <div class="form-error">{{ form.non_field_errors}}</div>

        {% for form_item in form %}
                <p>
                    <label class="form-label" for="{{ form_item.id_for_label }}">{{ form_item.label }}</label>
                    {{ form_item }}
                </p>
                <div class="form-error">{{ form_item.errors }}</div>
        {% endfor %}

        <!-- Button -->
        <div class="col-12">
            <ul class="actions form-button">
                <li><input type="submit" value="Change password" class="primary" /></li>
            </ul>
        </div>
    </form>

{% endblock %}

favourite_books_site/favouritebooks/users/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

    <p class="feedback-success">Password change successful</p>

    <ul class="actions special backhome-button">
          <li><a href="{% url 'users:profile' %}" class="button large">Return to Profile</a></li>
    </ul>

{% endblock %}

favourite_books_site/favouritebooks/users/templates/users/password_reset.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h2>Password reset</h2>

    <form method="post">
        {% csrf_token %}

        <div class="form-error">{{ form.non_field_errors}}</div>

        <p>Enter your E-mail address to send a password reset message.</p>

        {% for form_item in form %}
            <p>
                <label class="form-label" for="{{ form_item.id_for_label }}">{{ form_item.label }}</label>
                {{ form_item }}
            </p>
            <div class="form-error">{{ form_item.errors }}</div>
        {% endfor %}

        <!-- Button -->
        <div class="col-12">
            <ul class="actions form-button">
                <li><input type="submit" value="Reset password by e-mail" class="primary" /></li>
            </ul>
        </div>
    </form>

{% endblock %}

favourite_books_site/favouritebooks/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

    <p class="feedback-success">Password change successful</p>

    <ul class="actions special backhome-button">
          <li><a href="{% url 'users:profile' %}" class="button large">Login</a></li>
    </ul>

{% endblock %}

favourite_books_site/favouritebooks/users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h2>New password</h2>

    <form method="post">
        {% csrf_token %}

        <div class="form-error">{{ form.non_field_errors}}</div>
        {% for form_item in form %}
            <p>
                <label class="form-label" for="{{ form_item.id_for_label }}">{{ form_item.label }}</label>
                {{ form_item }}
            </p>
            <div class="form-error">{{ form_item.errors }}</div>
        {% endfor %}

        <!-- Button -->
        <div class="col-12">
            <ul class="actions form-button">
                <li><input type="submit" value="Save new password" class="primary" /></li>
            </ul>
        </div>
    </form>

{% endblock %}

favourite_books_site/favouritebooks/users/templates/users/password_reset_done.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h2>Password reset message</h2>

    <p>We’ve emailed you instructions for setting your password,
        if an account exists with the email you entered. You should receive them shortly.
        <br>
        If you don’t receive an email,
        please make sure you’ve entered the address you registered with, and check your spam folder.
    </p>

    <ul class="actions special backhome-button">
          <li><a href="{% url 'home' %}" class="button large">Return Home</a></li>
    </ul>

{% endblock %}

favourite_books_site/favouritebooks/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

favourite_books_site/favouritebooks/users/templates/users/profile.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h2>Profile: {{ user.username }} </h2>

    <form method="post">
        {% csrf_token %}

        <div class="form-error">{{ form.non_field_errors}}</div>

        {% for form_item in form %}
            <p>
                <label class="form-label" for="{{ form_item.id_for_label }}">{{ form_item.label }}</label>
                {{ form_item }}
            </p>
            <div class="form-error">{{ form_item.errors }}</div>
        {% endfor %}

        {% if user.has_usable_password %}
            <p><a href="{% url 'users:password_change' %}">Change password</a></p>
        {% endif %}

        <!-- Button -->
        <div class="col-12">
            <ul class="actions form-button">
                <li><input type="submit" value="Save changes" class="primary" /></li>
            </ul>
        </div>
    </form>

{% endblock %}

favourite_books_site/favouritebooks/users/templates/users/register.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h2>Register</h2>

    <form method="post">
        {% csrf_token %}

        <input type="hidden" name="next" value="{{ next }}" />
        <div class="form-error">{{ form.non_field_errors}}</div>
        {% for form_item in form %}
            <p>
                <label class="form-label" for="{{ form_item.id_for_label }}">{{ form_item.label }}</label>
                {{ form_item }}
            </p>
            <div class="form-error">{{ form_item.errors }}</div>
        {% endfor %}

        <!-- Button -->
        <div class="col-12">
            <ul class="actions form-button">
                <li><input type="submit" value="Register" class="primary" /></li>
            </ul>
        </div>

    </form>

{% endblock %}

favourite_books_site/favouritebooks/users/templates/users/register_success.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

    <p class="feedback-success">You have successfully registered on the site! To enter the system you need to authorize:</p>

    <ul class="actions special login-now">
          <li><a href="{% url 'users:login' %}" class="button large">Login now</a></li>
    </ul>

{% endblock %}