favourite_books_site/favouritebooks/books/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.BookMainPage.as_view(), name='home'),
    path('addbook/', views.AddBook.as_view(), name='add_book'),
    path('feedback/', views.Feedback.as_view(), name='feedback'),
    path('feedback-success/', views.FeedbackSuccess.as_view(), name='feedback_success'),
    path('books/', views.AllPublishedBooks.as_view(), name='books'),
    path('my-books/', views.UserBooks.as_view(), name='user_books'),
    path('my-books/tag/<str:tag_slug>/', views.UserBooksByGenres.as_view(), name='user_books_by_tag'),
    path('book/<slug:book_slug>/', views.DetailedBookInfo.as_view(), name='book'),
    path('comment/<int:comment_id>/delete/', views.DeleteCommentView.as_view(), name='delete_comment'),
    path('comment/<int:comment_id>/like/',views.LikeCommentView.as_view(), name='like_comment'),
    path('edit/<slug:book_slug>/', views.BookEdit.as_view(), name='edit_book'),
    path('edit-success/', views.BookEditSuccess.as_view(), name='edit_success'),
    path('delete/<slug:book_slug>/', views.BookDelete.as_view(), name='delete_book'),
    path('tag/<slug:tag_slug>/', views.BookGenres.as_view(), name='tag'),
]

favourite_books_site/favouritebooks/favouritebooks/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from books.views import page_not_found
from favouritebooks import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.ENABLE_DEBUG_TOOLBAR:
    urlpatterns += debug_toolbar_urls()

handler404 = page_not_found

admin.site.site_header = "Favourite Books administration panel"
admin.site.index_title = "Favourite Books administration"


favourite_books_site/favouritebooks/users/urls.py
from django.contrib.auth.views import (LogoutView, PasswordChangeDoneView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView)
from django.urls import path, reverse_lazy

from . import views
from .views import CustomPasswordResetView

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='home'), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('register-success/', views.RegisterUserSuccess.as_view(), name='register_success'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/',
        PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
        name='password_change_done'),
    path('password-reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/',
        PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
        name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                         success_url=reverse_lazy('users:password_reset_complete')),
        name='password_reset_confirm'),
    path('password_reset/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('profile/', views.UserProfile.as_view(), name='profile'),
]

favourite_books_site/favouritebooks/templates/includes/footer.html
{% load static %}

<footer id="footer">
    <section class="split contact">
        <section>
            <h3 class="social-footer">Social:</h3>
            <ul class="icons alt">
                <li><a href="#" class="icon brands alt fa-instagram">
                    <span class="label">Instagram</span></a>
                </li>
                <li><a href="https://github.com/ArtemKhov" class="icon brands alt fa-github" target="_blank">
                    <span class="label">GitHub</span></a>
                </li>
            </ul>
            <!-- Copyright -->
            <h3 class="copyright"><a href="\">&copy; 2024-2025 My Favourite Books</a></h3>
        </section>
    </section>
</footer>

favourite_books_site/favouritebooks/templates/includes/header.html
<header id="header">
    <a href="\" class="logo">My Favourite Books</a>
</header>

favourite_books_site/favouritebooks/templates/includes/nav.html
{% load static %}

<nav id="nav">
    <ul class="links">
        {% for navbar_item in navbar %}
            {% if request.user.is_authenticated and navbar_item.title == 'My books' %}
                <li><a href="{% url navbar_item.url_name %}">{{ navbar_item.title }}</a></li>
            {% elif navbar_item.title != 'My books' %}
                <li><a href="{% url navbar_item.url_name %}">{{ navbar_item.title }}</a></li>
            {% endif %}
        {% endfor %}
    </ul>

    <ul class="icons">

        {% if user.is_authenticated %}
            <li>
                <a class="user-block" href="{% url 'users:profile' %}">
                    <button class="button primary profile mobile">{{ user.username }}</button>
                </a>
            </li>
            <li>
                <form method="post" action="{% url 'users:logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="button logout mobile">Logout</button>
                </form>
            </li>
        {% else %}
            <li>
                <a class="login-block" href="{% url 'users:login' %}">
                    <button class="button primary login mobile">Login</button>
                </a>
            </li>
            <li>
                <a class="register-block" href="{% url 'users:register' %}">
                    <button class="button register mobile">Register</button>
                </a>
            </li>
        {% endif %}

        <li><a href="#" class="icon brands fa-instagram">
            <span class="label">Instagram</span></a>
        </li>
        <li><a href="https://github.com/ArtemKhov" class="icon brands fa-github" target="_blank">
            <span class="label">GitHub</span></a>
        </li>
    </ul>
</nav>

<nav id="nav1">

    <ul class="icons">
        {% if user.is_authenticated %}
            <li>
                <a class="user-block-mobile" href="{% url 'users:profile' %}">
                    <button class="button primary profile mobile-navbar">{{ user.username }}</button>
                </a>
            </li>
            <li>
                <form method="post" action="{% url 'users:logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="button logout mobile-navbar">Logout</button>
                </form>
            </li>
        {% else %}
            <li>
                <a class="login-block-mobile" href="{% url 'users:login' %}">
                    <button class="button primary login mobile-navbar">Login</button>
                </a>
            </li>
            <li>
                <a class="register-block-mobile" href="{% url 'users:register' %}">
                    <button class="button register mobile-navbar">Register</button>
                </a>
            </li>
        {% endif %}
    </ul>
</nav>